### ISSUE TITLE
Failed to fetch, just started today was working yesterday

### ISSUE THREAD

**Issue by cryptocoop** [auterium/genopets-harvester-tracker#5]
Hello, I really like what you have made, Super useful! I had been using it the past couple days, but today when I went to execute it (from the command window with npm start) it loads the webpage, but when I try to search the wallet address it reports 
'Localhost error: TypeError: Failed to fetch'
I verified the local server was pointing at that folder (even though I didn't have to do that yesterday). 
I tried to install the depenencies and run it on a different computer on a different network and got the same error. Im not sure if it is a execution error or a block chain issue.
Cheers!

**Comment by Aditya7748** [comment]
Facing same issue

**Comment by cryptocoop** [comment]
It worked today, Not sure what changed. But its back to Fetching!

**Comment by Aditya7748** [comment]
> 

It's working perfectly thanks a lot Bhaskar bhai❤
